services:

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - docker_network
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/wp-config.php"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - docker_network
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - docker_network
    restart: always

networks:
  docker_network:
    driver: bridge
    name: inception-network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rammisse/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rammisse/data/wordpress